# Generated by Django 4.0.2 on 2022-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('external_id', models.CharField(max_length=50)),
                ('gate_open_url', models.CharField(max_length=100)),
                ('lock_open_url', models.CharField(max_length=100)),
            ],
        ),
    ]
