# Generated by Django 4.0.2 on 2022-03-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0002_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
