# Generated by Django 4.0.2 on 2022-03-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0003_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='gate_open_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='lock_open_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
