# Generated by Django 4.0.2 on 2022-03-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0005_parkingspot_alter_site_gate_open_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('scooter', 'Scooter'), ('bike', 'Bike')], default='bike', max_length=30),
        ),
    ]
