# Generated by Django 4.0.2 on 2022-03-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0006_alter_parkingspot_spot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='station_admin.site'),
            preserve_default=False,
        ),
    ]
