# Generated by Django 4.0.2 on 2022-03-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0007_parkingspot_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('max_time_mins', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='parking_charge_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_charge_rule', to='station_admin.chargerule'),
        ),
        migrations.AddField(
            model_name='site',
            name='rent_charge_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_charge_rule', to='station_admin.chargerule'),
        ),
    ]
