# Generated by Django 4.0.2 on 2022-03-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0009_chargerule_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargerule',
            name='site',
        ),
    ]
