# Generated by Django 4.0.2 on 2022-03-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0012_alter_qrcode_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_admin.qrcode'),
        ),
    ]
