# Generated by Django 4.0.2 on 2022-04-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0015_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_admin.parkingspot')),
            ],
            options={
                'db_table': 'parking_session',
            },
        ),
    ]
