# Generated by Django 4.0.2 on 2022-04-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0017_parkingsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='charge_rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='station_admin.chargerule'),
            preserve_default=False,
        ),
    ]
