# Generated by Django 4.0.2 on 2022-04-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0018_parkingsession_charge_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50)),
                ('spot_type', models.CharField(choices=[('scooter', 'Scooter'), ('bike', 'Bike')], default='bike', max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_admin.site')),
            ],
        ),
    ]
