# Generated by Django 4.0.2 on 2022-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0019_rentspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='lock_close_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
