# Generated by Django 4.0.2 on 2022-04-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0020_site_lock_close_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_type', models.CharField(choices=[('scooter', 'Scooter'), ('bike', 'Bike')], default='bike', max_length=50)),
                ('current_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_admin.rentspot')),
            ],
        ),
    ]
