# Generated by Django 4.0.2 on 2022-04-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('station_admin', '0022_alter_vehicle_current_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('charge_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_admin.chargerule')),
                ('returned_to_spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_to_spot', to='station_admin.rentspot')),
                ('taken_from_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_from_spot', to='station_admin.rentspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
