# Generated by Django 4.0.2 on 2022-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0025_alter_chargerule_price_alter_userprofile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
