# Generated by Django 4.0.2 on 2022-04-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_admin', '0026_alter_userprofile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='vehicle', max_length=50),
            preserve_default=False,
        ),
    ]
